# Generated by Django 3.2.2 on 2021-06-12 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210612_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 12, 14, 57, 27, 688278, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2021, 6, 12, 14, 57, 33, 478277, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
